In [1]:
import pandas as pd
import os

#step 1
#Load the messy CSV

In [3]:
file_path = r"C:\Users\Raja\OneDrive\Desktop\cafe_data_cleaning\data\processed\cafe_sales_cleaned.csv"
df = pd.read_csv(file_path)

#step 2

In [4]:
df.shape

(10000, 11)

#step 3

In [5]:
df.size

110000

#step 4

In [6]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Day of Week,Month,Year
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,Friday,9,2023
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,Tuesday,5,2023
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19,Wednesday,7,2023
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Unknown,2023-04-27,Thursday,4,2023
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,Sunday,6,2023

#step 5

In [7]:
df.dtypes

Transaction ID          str
Item                    str
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
Day of Week             str
Month                 int64
Year                  int64
dtype: object

#step 6

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              10000 non-null  str
 2   Quantity          10000 non-null  float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  str
 6   Location          10000 non-null  str
 7   Transaction Date  10000 non-null  str
 8   Day of Week       10000 non-null  str
 9   Month             10000 non-null  int64
 10  Year              10000 non-null  int64
dtypes: float64(3), int64(2), str(6)
memory usage: 1.3 MB

#step 7

In [9]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Day of Week         0
Month               0
Year                0
dtype: int64

# step 8

In [10]:
df.describe()

           Quantity  Price Per Unit  Total Spent         Month     Year
count  10000.000000     10000.00000  10000.00000  10000.000000  10000.0
mean       3.027100         2.95265      8.87795      6.545900   2023.0
std        1.384614         1.24396      5.86059      3.370642      0.0
min        1.000000         1.00000      1.00000      1.000000   2023.0
25%        2.000000         2.00000      4.00000      4.000000   2023.0
50%        3.000000         3.00000      8.00000      7.000000   2023.0
75%        4.000000         4.00000     12.00000      9.000000   2023.0
max        5.000000         5.00000     25.00000     12.000000   2023.0

# step 9
#count of unique values in all text/categorical columns.

In [11]:
print(df.select_dtypes(include='object').nunique())

Transaction ID      10000
Item                    8
Payment Method          3
Location                3
Transaction Date      365
Day of Week             7
dtype: int64

C:\Users\Raja\AppData\Local\Temp\ipykernel_5788\4064812227.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include='object').nunique())

#step 10
#to view unique values in a specific column, e.g., 'Item'

In [12]:
print(df['Item'].unique())

<ArrowStringArray>
['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Juice', 'Sandwich', 'Tea']
Length: 8, dtype: str